### ISSUE TITLE
Error while installing the node

### ISSUE THREAD

**Issue by fedex03** [fsteccanella/node-red-contrib-as400#1]
Hi @fsteccanella,

I'm tring to install your AS400 node on Node-Red (running on docker) but I get this error:

`
----------------------------------------------------------
2021-12-03T10:38:09.827Z Install : node-red-contrib-as400 0.0.2

2021-12-03T10:38:09.672Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-as400@0.0.2
2021-12-03T10:38:33.467Z [out] 
2021-12-03T10:38:33.467Z [out] > java@0.9.1 install /data/node_modules/java
2021-12-03T10:38:33.467Z [out] > node-gyp rebuild
2021-12-03T10:38:33.467Z [out] 
2021-12-03T10:38:38.847Z [err] [node-java] Error: not found: javac
2021-12-03T10:38:38.848Z [err] gyp: Call to 'node findJavaHome.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
2021-12-03T10:38:38.868Z [err] gyp
2021-12-03T10:38:38.868Z [err]  ERR! configure error 
2021-12-03T10:38:38.870Z [err] gyp 
2021-12-03T10:38:38.870Z [err] ERR! stack Error: `gyp` failed with exit code: 1
2021-12-03T10:38:38.870Z [err] gyp ERR!
2021-12-03T10:38:38.870Z [err]  stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
2021-12-03T10:38:38.870Z [err] gyp ERR! 
2021-12-03T10:38:38.871Z [err] stack     at ChildProcess.emit (events.js:400:28)
2021-12-03T10:38:38.871Z [err] gyp ERR! stack
2021-12-03T10:38:38.871Z [err]      at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
2021-12-03T10:38:38.871Z [err] gyp 
2021-12-03T10:38:38.872Z [err] ERR! System Linux 4.9.75-rt60-preempt-rt
2021-12-03T10:38:38.872Z [err] gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-12-03T10:38:38.872Z [err] gyp ERR! cwd /data/node_modules/java
2021-12-03T10:38:38.872Z [err] gyp ERR! node -v v14.18.2
2021-12-03T10:38:38.872Z [err] gyp ERR! node-gyp -v v5.1.0
2021-12-03T10:38:38.873Z [err] gyp ERR! not ok
2021-12-03T10:38:38.873Z [err]  
2021-12-03T10:38:39.510Z [err] npm 
2021-12-03T10:38:39.510Z [err] ERR! code ELIFECYCLE
2021-12-03T10:38:39.510Z [err] npm ERR!
2021-12-03T10:38:39.510Z [err]  errno 1
2021-12-03T10:38:39.546Z [err] npm ERR!
2021-12-03T10:38:39.546Z [err]  java@0.9.1 install: `node-gyp rebuild`
2021-12-03T10:38:39.546Z [err] npm ERR!
2021-12-03T10:38:39.546Z [err]  Exit status 1
2021-12-03T10:38:39.546Z [err] npm
2021-12-03T10:38:39.546Z [err]  ERR! 
2021-12-03T10:38:39.546Z [err] npm 
2021-12-03T10:38:39.547Z [err] ERR! Failed at the java@0.9.1 install script.
2021-12-03T10:38:39.547Z [err] npm
2021-12-03T10:38:39.547Z [err]  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-12-03T10:38:39.563Z [err] 
2021-12-03T10:38:39.563Z [err] npm ERR! A complete log of this run can be found in:
2021-12-03T10:38:39.563Z [err] npm ERR!     /data/.npm/_logs/2021-12-03T10_38_39_555Z-debug.log
2021-12-03T10:38:39.581Z rc=1
`

This error could be related to my Node-Red?
I tried to install it on Node-Red v2.1.4 and v0.18.7.

I hope I can run your node on my hardware because I'm looking to find a way to communicate with an A S/400.

Thanks in advance for your time.

Best regards,
Federico

**Comment by fsteccanella** [comment]
Hi @fedex03 
I would say that probably the issue is caused by missing jdk and/or missing JAVA_HOME variable

> [node-java] Error: not found: javac
> gyp: Call to 'node findJavaHome.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
